replace firmid = 	"5758711"	if raisonsociale == 	"SOCABEG"
replace firmid = 	"13730"	if raisonsociale == 	"ENTREPRISE GENERALE DE BATIMENT R. BADARACCHI SA"
replace firmid = 	"110255"	if raisonsociale == 	"CENTRE INTERNATIONAL DU COMMERCE EXT�RIEUR DU S�N�GAL"
replace firmid = 	"133596"	if raisonsociale == 	"DR TALAL ATTYE"
replace firmid = 	"14423"	if raisonsociale == 	"INDEPENDANCE IMMOBILIERE GESTION SARL"
replace firmid = 	"395360"	if raisonsociale == 	"BUREAU GAUDILLAT"
replace firmid = 	"179152"	if raisonsociale == 	"TRANSGAYE SARL"
replace firmid = 	"89525"	if raisonsociale == 	"AFRIC SECURIM SARL"
replace firmid = 	"144402"	if raisonsociale == 	"VET SERVICE"
replace firmid = 	"166985"	if raisonsociale == 	"GIE DIAMBAR"
replace firmid = 	"285222"	if raisonsociale == 	"STABURO SARL"
replace firmid = 	"390815"	if raisonsociale == 	"STE DEXPERTISE ET CONTROLE INDUSTRIEL SARL"
replace firmid = 	"80820"	if raisonsociale == 	"CAMPUS"
replace firmid = 	"344911"	if raisonsociale == 	"GRAPHI PLUS SARL BG1127"
replace firmid = 	"4471372"	if raisonsociale == 	"MOI MOUSSA MBACKE"
replace firmid = 	"4471372"	if raisonsociale == 	"MAITRE MOUSSA MBACKE"
replace firmid = 	"4471372"	if raisonsociale == 	"ME MOUSSA MBACKE"
replace firmid = 	"346298"	if raisonsociale == 	"MMA CONSULTING SENEGAL"
replace firmid = 	"2016097"	if raisonsociale == 	"CECOMAR SARL/ EXPERT MARITIME"
replace firmid = 	"484709"	if raisonsociale == 	"SYNERGIES AUDIT CONSEILS"
replace firmid = 	"242298"	if raisonsociale == 	"COMPAGNIE DE GESTION FINANCIERE ET DE BOURSE CGF BOURSE"
replace firmid = 	"242298"	if raisonsociale == 	"C.G.F.BOURSE"
replace firmid = 	"15827"	if raisonsociale == 	"SOCIETE COMMERCIALE ET INDUSTRIELLE DAKAROISE"
replace firmid = 	"18110"	if raisonsociale == 	"BANQUE INTERNATIONAL POUR LE COMMERCE ET INDUSTRIE DU SENEGAL"
replace firmid = 	"18110"	if raisonsociale == 	"BANQUE INTERNATIONAL POUR LE COMMERCE ET INDUSTRIE DU SENEGAL"
replace firmid = 	"2262806"	if raisonsociale == 	"BISCUITERIE MODERNE SENEGALAISE"
replace firmid = 	"2926379"	if raisonsociale == 	"ASTORIA SARL"
replace firmid = 	"2358134"	if raisonsociale == 	"2D BUSINESS CONSULTING"
replace firmid = 	"4458213"	if raisonsociale == 	"TRANSPAPS SA"
replace firmid = 	"83171"	if raisonsociale == 	"SENEGALAISE DINDUSTRIE ET DE COMMERCE SA"
replace firmid = 	"2661636"	if raisonsociale == 	"RMA SENEGAL/ COMPTABLE"
replace firmid = 	"2838889"	if raisonsociale == 	"GLOBUS ITALIA SARL"
replace firmid = 	"4652831"	if raisonsociale == 	"SOCIETE AFRICAINE DE DISTRIBUTION SNAD SUARL  BG2208"
replace firmid = 	"3064251"	if raisonsociale == 	"GLOBAL PERFORMANCE CONSULTING"
replace firmid = 	"6137089"	if raisonsociale == 	"SARL ECCOTRA"
replace firmid = 	"34520"	if raisonsociale == 	"OCEAN ATLANTIC CITY"
replace firmid = 	"34520"	if raisonsociale == 	"OCEAN ATLANTIC CITY        BG3007"
replace firmid = 	"2489195"	if raisonsociale == 	"BLUE FISH"
replace firmid = 	"4147949"	if raisonsociale == 	"FINANCE EXPERTISE TECHNOLOGIE"
replace firmid = 	"4175247"	if raisonsociale == 	"HOME TECHNOLOGIE"
replace firmid = 	"2952051"	if raisonsociale == 	"STEPHANE SERGE SANCHEZ"
replace firmid = 	"5770707"	if raisonsociale == 	"CABINET MEDICAL KERMEL SARL"
replace firmid = 	"5241550"	if raisonsociale == 	"PRISMA INDUSTRIES SARL"
replace firmid = 	"45618"	if raisonsociale == 	"INTERNATIONAL TRADING OIL AND COMMODITIES CORPORATION BGCGE COM2 005"
replace firmid = 	"45618"	if raisonsociale == 	"INTERNATIONAL TRADING OIL AND COMMODITIES CORPORATION SA"
replace firmid = 	"4710291"	if raisonsociale == 	"JAHN TRADING SUARL"
replace firmid = 	"4736784"	if raisonsociale == 	"AGROPHARM"
replace firmid = 	"4736784"	if raisonsociale == 	"AGROPHARM"
replace firmid = 	"2813641"	if raisonsociale == 	"MR IBRAHIMA SOURANG"
replace firmid = 	"4176097"	if raisonsociale == 	"GIE TECHNIQUE PLASTIQUE"
replace firmid = 	"5963302"	if raisonsociale == 	"MAXAM SENEGAL SUARL"
replace firmid = 	"6087226"	if raisonsociale == 	"SALAMA FIKIRA SENEGAL"
replace firmid = 	"4677946"	if raisonsociale == 	"SERTEM IMMO SA"
replace firmid = 	"4206373"	if raisonsociale == 	"MAINTENANCE PNEUS SUARL"
replace firmid = 	"4206373"	if raisonsociale == 	"MAINTENANCE PNEUS SUARL"
replace firmid = 	"4151544"	if raisonsociale == 	"AGENCE POUR LA REINSERTION SOCIALE DES MILITAIRES"
replace firmid = 	"2268581"	if raisonsociale == 	"AL MAKARU AL ASMA"
replace firmid = 	"6248761"	if raisonsociale == 	"AMITI OVERSEAS SUARL"
replace firmid = 	"305757"	if raisonsociale == 	"CHOCOSEN"
replace firmid = 	"4620599"	if raisonsociale == 	"CLINIQUE DU CAP SARL"
replace firmid = 	"6508800"	if raisonsociale == 	"DAKAR ATLANTIC & INTERNATIONAL BUSINESS SUARL"
replace firmid = 	"4318540"	if raisonsociale == 	"ENTRACOM"
replace firmid = 	"58736"	if strpos(raisonsociale , "EQUIPEMENT SA GTHE SA") > 0 
replace firmid = 	"2466002"	if raisonsociale == 	"INGENIEURIE REPRESENTATION ET SERVICES AERONAUTIQUE"
replace firmid = 	"6554720"	if raisonsociale == 	"IZITAP SA"
replace firmid = 	"5715795"	if raisonsociale == 	"LANDTEK SARL"
replace firmid = 	"4725026"	if raisonsociale == 	"MARIEME MEGA SERVICES SARL"
replace firmid = 	"312702"	if raisonsociale == 	"ME BABA DIOP"
replace firmid = 	"4268894"	if raisonsociale == 	"MINCOM WEST AFRICA"
replace firmid = 	"2069559"	if raisonsociale == 	"MODOU GUEYE"
replace firmid = 	"4099786"	if raisonsociale == 	"MODOU MBACKE THIAL DAROU KHOUDOSS INDUSTRIE SUARL"
replace firmid = 	"83048"	if strpos(raisonsociale , "ASSAINISSEMENT DU SENEGAL ONAS") > 0 
replace firmid = 	"4354750"	if raisonsociale == 	"ORICA SENEGAL"
replace firmid = 	"2988882"	if raisonsociale == 	"PARTICIPATIONS GENERALES AFRICAINES SENEGAL SA"
replace firmid = 	"2167709"	if raisonsociale == 	"SAVE THE CHILDREN INTERNATIONAL"
replace firmid = 	"6331871"	if raisonsociale == 	"SENE GREEN SOLUTIONS SARL"
replace firmid = 	"118829"	if raisonsociale == 	"SENEGALAISE DE COSMETIQUES SARL"
replace firmid = 	"2521690"	if raisonsociale == 	"SOCIETE AFRICAINE DE DISTRIBUTION DE PRODUITS ALIMENTAIRES SARL"
replace firmid = 	"18855"	if 	strpos(raisonsociale, "ENTREPOSAGE") > 0 
replace firmid = 	"130253"	if raisonsociale == 	"SOCIETE DETUDE ET DE GESTION MALADIE SENEGAL"
replace firmid = 	"2077346"	if raisonsociale == 	"SOCIETE DINVESTISSEMENT ET DE PROMOTION IMMOBILIERE"
replace firmid = 	"2501139"	if raisonsociale == 	"SOCIETE SENEGALAISE DES CARRIERES"
replace firmid = 	"5296323"	if raisonsociale == 	"SOPE NABY DISTRIBUTION COMMODITIES SARL"
replace firmid = 	"5702643"	if raisonsociale == 	"TERANGA SEAFOOD INTERNATIONAL SA"
replace firmid = 	"6011291"	if raisonsociale == 	"WOODSIDE ENERGYSENEGAL B.V."
replace firmid = 	"6011291"	if raisonsociale == 	"WOODSIDE ENERGYSENEGAL PTY LTD"

replace ninea = 	"5758711"	if raisonsociale == 	"SOCABEG"
replace ninea = 	"13730"	if raisonsociale == 	"ENTREPRISE GENERALE DE BATIMENT R. BADARACCHI SA"
replace ninea = 	"110255"	if raisonsociale == 	"CENTRE INTERNATIONAL DU COMMERCE EXT�RIEUR DU S�N�GAL"
replace ninea = 	"133596"	if raisonsociale == 	"DR TALAL ATTYE"
replace ninea = 	"14423"	if raisonsociale == 	"INDEPENDANCE IMMOBILIERE GESTION SARL"
replace ninea = 	"395360"	if raisonsociale == 	"BUREAU GAUDILLAT"
replace ninea = 	"179152"	if raisonsociale == 	"TRANSGAYE SARL"
replace ninea = 	"89525"	if raisonsociale == 	"AFRIC SECURIM SARL"
replace ninea = 	"144402"	if raisonsociale == 	"VET SERVICE"
replace ninea = 	"166985"	if raisonsociale == 	"GIE DIAMBAR"
replace ninea = 	"285222"	if raisonsociale == 	"STABURO SARL"
replace ninea = 	"390815"	if raisonsociale == 	"STE DEXPERTISE ET CONTROLE INDUSTRIEL SARL"
replace ninea = 	"80820"	if raisonsociale == 	"CAMPUS"
replace ninea = 	"344911"	if raisonsociale == 	"GRAPHI PLUS SARL BG1127"
replace ninea = 	"4471372"	if raisonsociale == 	"MOI MOUSSA MBACKE"
replace ninea = 	"4471372"	if raisonsociale == 	"MAITRE MOUSSA MBACKE"
replace ninea = 	"4471372"	if raisonsociale == 	"ME MOUSSA MBACKE"
replace ninea = 	"346298"	if raisonsociale == 	"MMA CONSULTING SENEGAL"
replace ninea = 	"2016097"	if raisonsociale == 	"CECOMAR SARL/ EXPERT MARITIME"
replace ninea = 	"484709"	if raisonsociale == 	"SYNERGIES AUDIT CONSEILS"
replace ninea = 	"242298"	if raisonsociale == 	"COMPAGNIE DE GESTION FINANCIERE ET DE BOURSE CGF BOURSE"
replace ninea = 	"242298"	if raisonsociale == 	"C.G.F.BOURSE"
replace ninea = 	"15827"	if raisonsociale == 	"SOCIETE COMMERCIALE ET INDUSTRIELLE DAKAROISE"
replace ninea = 	"18110"	if raisonsociale == 	"BANQUE INTERNATIONAL POUR LE COMMERCE ET INDUSTRIE DU SENEGAL"
replace ninea = 	"18110"	if raisonsociale == 	"BANQUE INTERNATIONAL POUR LE COMMERCE ET INDUSTRIE DU SENEGAL"
replace ninea = 	"2262806"	if raisonsociale == 	"BISCUITERIE MODERNE SENEGALAISE"
replace ninea = 	"2926379"	if raisonsociale == 	"ASTORIA SARL"
replace ninea = 	"2358134"	if raisonsociale == 	"2D BUSINESS CONSULTING"
replace ninea = 	"4458213"	if raisonsociale == 	"TRANSPAPS SA"
replace ninea = 	"83171"	if raisonsociale == 	"SENEGALAISE DINDUSTRIE ET DE COMMERCE SA"
replace ninea = 	"2661636"	if raisonsociale == 	"RMA SENEGAL/ COMPTABLE"
replace ninea = 	"2838889"	if raisonsociale == 	"GLOBUS ITALIA SARL"
replace ninea = 	"4652831"	if raisonsociale == 	"SOCIETE AFRICAINE DE DISTRIBUTION SNAD SUARL  BG2208"
replace ninea = 	"3064251"	if raisonsociale == 	"GLOBAL PERFORMANCE CONSULTING"
replace ninea = 	"6137089"	if raisonsociale == 	"SARL ECCOTRA"
replace ninea = 	"34520"	if raisonsociale == 	"OCEAN ATLANTIC CITY"
replace ninea = 	"34520"	if raisonsociale == 	"OCEAN ATLANTIC CITY        BG3007"
replace ninea = 	"2489195"	if raisonsociale == 	"BLUE FISH"
replace ninea = 	"4147949"	if raisonsociale == 	"FINANCE EXPERTISE TECHNOLOGIE"
replace ninea = 	"4175247"	if raisonsociale == 	"HOME TECHNOLOGIE"
replace ninea = 	"2952051"	if raisonsociale == 	"STEPHANE SERGE SANCHEZ"
replace ninea = 	"5770707"	if raisonsociale == 	"CABINET MEDICAL KERMEL SARL"
replace ninea = 	"5241550"	if raisonsociale == 	"PRISMA INDUSTRIES SARL"
replace ninea = 	"45618"	if raisonsociale == 	"INTERNATIONAL TRADING OIL AND COMMODITIES CORPORATION BGCGE COM2 005"
replace ninea = 	"45618"	if raisonsociale == 	"INTERNATIONAL TRADING OIL AND COMMODITIES CORPORATION SA"
replace ninea = 	"4710291"	if raisonsociale == 	"JAHN TRADING SUARL"
replace ninea = 	"4736784"	if raisonsociale == 	"AGROPHARM"
replace ninea = 	"4736784"	if raisonsociale == 	"AGROPHARM"
replace ninea = 	"2813641"	if raisonsociale == 	"MR IBRAHIMA SOURANG"
replace ninea = 	"4176097"	if raisonsociale == 	"GIE TECHNIQUE PLASTIQUE"
replace ninea = 	"5963302"	if raisonsociale == 	"MAXAM SENEGAL SUARL"
replace ninea = 	"6087226"	if raisonsociale == 	"SALAMA FIKIRA SENEGAL"
replace ninea = 	"4677946"	if raisonsociale == 	"SERTEM IMMO SA"
replace ninea = 	"4206373"	if raisonsociale == 	"MAINTENANCE PNEUS SUARL"
replace ninea = 	"4206373"	if raisonsociale == 	"MAINTENANCE PNEUS SUARL"
replace ninea = 	"4151544"	if raisonsociale == 	"AGENCE POUR LA REINSERTION SOCIALE DES MILITAIRES"
replace ninea = 	"2268581"	if raisonsociale == 	"AL MAKARU AL ASMA"
replace ninea = 	"6248761"	if raisonsociale == 	"AMITI OVERSEAS SUARL"
replace ninea = 	"305757"	if raisonsociale == 	"CHOCOSEN"
replace ninea = 	"4620599"	if raisonsociale == 	"CLINIQUE DU CAP SARL"
replace ninea = 	"6508800"	if raisonsociale == 	"DAKAR ATLANTIC & INTERNATIONAL BUSINESS SUARL"
replace ninea = 	"4318540"	if raisonsociale == 	"ENTRACOM"
replace ninea = 	"58736"	if strpos(raisonsociale , "EQUIPEMENT SA GTHE SA") > 0 
replace ninea = 	"2466002"	if raisonsociale == 	"INGENIEURIE REPRESENTATION ET SERVICES AERONAUTIQUE"
replace ninea = 	"6554720"	if raisonsociale == 	"IZITAP SA"
replace ninea = 	"5715795"	if raisonsociale == 	"LANDTEK SARL"
replace ninea = 	"4725026"	if raisonsociale == 	"MARIEME MEGA SERVICES SARL"
replace ninea = 	"312702"	if raisonsociale == 	"ME BABA DIOP"
replace ninea = 	"4268894"	if raisonsociale == 	"MINCOM WEST AFRICA"
replace ninea = 	"2069559"	if raisonsociale == 	"MODOU GUEYE"
replace ninea = 	"4099786"	if raisonsociale == 	"MODOU MBACKE THIAL DAROU KHOUDOSS INDUSTRIE SUARL"
replace ninea = 	"83048"	if strpos(raisonsociale , "ASSAINISSEMENT DU SENEGAL ONAS") > 0 
replace ninea = 	"4354750"	if raisonsociale == 	"ORICA SENEGAL"
replace ninea = 	"2988882"	if raisonsociale == 	"PARTICIPATIONS GENERALES AFRICAINES SENEGAL SA"
replace ninea = 	"2167709"	if raisonsociale == 	"SAVE THE CHILDREN INTERNATIONAL"
replace ninea = 	"6331871"	if raisonsociale == 	"SENE GREEN SOLUTIONS SARL"
replace ninea = 	"118829"	if raisonsociale == 	"SENEGALAISE DE COSMETIQUES SARL"
replace ninea = 	"2521690"	if raisonsociale == 	"SOCIETE AFRICAINE DE DISTRIBUTION DE PRODUITS ALIMENTAIRES SARL"
replace ninea = 	"18855"	if 	strpos(raisonsociale, "ENTREPOSAGE") > 0 
replace ninea = 	"130253"	if raisonsociale == 	"SOCIETE DETUDE ET DE GESTION MALADIE SENEGAL"
replace ninea = 	"2077346"	if raisonsociale == 	"SOCIETE DINVESTISSEMENT ET DE PROMOTION IMMOBILIERE"
replace ninea = 	"2501139"	if raisonsociale == 	"SOCIETE SENEGALAISE DES CARRIERES"
replace ninea = 	"5296323"	if raisonsociale == 	"SOPE NABY DISTRIBUTION COMMODITIES SARL"
replace ninea = 	"5702643"	if raisonsociale == 	"TERANGA SEAFOOD INTERNATIONAL SA"
replace ninea = 	"6011291"	if raisonsociale == 	"WOODSIDE ENERGYSENEGAL B.V."
replace ninea = 	"6011291"	if raisonsociale == 	"WOODSIDE ENERGYSENEGAL PTY LTD"
