*****************************************************************************************
**         Project name: ALGORITHMS AND BUREAUCRATS: EVIDENCE FROM TAX AUDIT SELECTION IN SENEGAL
**         Authors: Pierre Bachas, Anne Brockmeyer, Alipio Ferreira, Bassirou Sarr
**         RA: Roldan Enamorado
**         May 2026
*****************************************************************************************

*****************
** DESCRIPTION **
*****************

* This do-file recreates the two Figure 4 predicted-rank diagnostics for
* selected full audits using the predicted-rank exports generated by:
* Code Analyse data/Replication R/07_Optimization_Exercise_Unweighted_Top5_Revision.R
*
* The x-axis uses within-list predicted-priority deciles. Decile 10 is the
* highest predicted priority within the audit-type-by-office-by-year list;
* decile 1 is the lowest predicted priority.

version 17
set more off
clear all
capture set scheme stcolor
if _rc {
    set scheme s2color
}

global check = 1

*****************
** DIRECTORIES **
*****************
if strpos(lower("`c(username)'"),"49354415") {
    global rootdir "C:\Users\49354415\Dropbox\Trabalho\2017 WB\Senegal tax audits"
}
if strpos(lower("`c(username)'"),"user") {
    global rootdir "C:\Users\User\Dropbox\Senegal tax audits"
}
if strpos(lower("`c(username)'"),"wb648862") {
    global rootdir "C:\Users\wb648862\Dropbox\Senegal tax audits"
}
if "$rootdir" == "" {
    global rootdir "C:\Users\User\Dropbox\Senegal tax audits"
}

global rawdata "$rootdir"
global analysisdata "$rootdir\Analysis all data\replication_package\Working data"
global wastedata "$rootdir\Analysis all data\replication_package\Intermediate data"
global output "$rootdir\Analysis all data\replication_package\Output"

if $check == 1 {
    global output "C:\Users\User\Documents\Projects\Senegal-Tax-Audit\Output"
    if strpos(lower("`c(username)'"),"wb648862") {
        global output "C:\Users\wb648862\Documents\Projects\Senegal Tax Audits\Output"
    }
}

local rank_input_b1 "$analysisdata\fullaudits_predicted_rank_bureauyear_07_b1_allcases.dta"
local rank_input_top5 "$analysisdata\fullaudits_predicted_rank_bureauyear_07_b2b3_top5excluded.dta"

capture program drop build_rank_figure4
program define build_rank_figure4
    syntax, Rankinput(string) [Outputsuffix(string)]

    ************************************************************
    * 1. Load selected non-safety full audits
    ************************************************************
    use "`rankinput'", clear

    foreach var in predicted_rank_order_bureauyear y2 algorithm dgid selection safeties bureau_detailed selectionyear {
        capture confirm variable `var'
        if _rc {
            di as error "Required variable `var' not found in `rankinput'."
            exit 111
        }
    }

    keep if selection == 1
    drop if safeties == 1

    capture confirm variable controle
    if !_rc {
        keep if controle == 2
        egen predicted_rank_list_id = group(controle bureau_detailed selectionyear), missing
    }
    else {
        egen predicted_rank_list_id = group(bureau_detailed selectionyear), missing
    }

    drop if missing(predicted_rank_order_bureauyear)

    bysort predicted_rank_list_id: egen predicted_rank_list_n = count(predicted_rank_order_bureauyear)
    bysort predicted_rank_list_id: egen predicted_rank_list_max = max(predicted_rank_order_bureauyear)

    gen predicted_priority_decile = .
    replace predicted_priority_decile = 10 if predicted_rank_list_n == 1
    replace predicted_priority_decile = 10 - floor(10 * (predicted_rank_order_bureauyear - 1) / (predicted_rank_list_n - 1)) ///
        if predicted_rank_list_n > 1
    replace predicted_priority_decile = 1 if predicted_priority_decile < 1 & predicted_priority_decile != .
    replace predicted_priority_decile = 10 if predicted_priority_decile > 10 & predicted_priority_decile != .
    label var predicted_priority_decile "Predicted priority decile, 10 = highest priority"

    assert inrange(predicted_priority_decile, 1, 10) if predicted_priority_decile != .
    assert predicted_priority_decile == 10 if predicted_rank_order_bureauyear == 1
    assert predicted_priority_decile == 1 if predicted_rank_list_n > 1 & predicted_rank_order_bureauyear == predicted_rank_list_max

    tempfile fullaudits
    save `fullaudits', replace

    ************************************************************
    * 2. Panel A: Execution rate by predicted-priority decile
    ************************************************************
    use `fullaudits', clear
    keep if !missing(y2)

    collapse (mean) execution_rate = y2 (sd) sd_execution = y2 (count) n_execution = y2, by(predicted_priority_decile)
    replace sd_execution = 0 if missing(sd_execution)
    gen se_execution = sd_execution / sqrt(n_execution)
    gen execution_lower = max(0, execution_rate - 1.96 * se_execution)
    gen execution_upper = min(1, execution_rate + 1.96 * se_execution)
    replace execution_rate = 100 * execution_rate
    replace execution_lower = 100 * execution_lower
    replace execution_upper = 100 * execution_upper

    sort predicted_priority_decile

    twoway ///
        (rarea execution_lower execution_upper predicted_priority_decile, fcolor(red) fintensity(15) lcolor(red) lwidth(vvthin)) || ///
        (connected execution_rate predicted_priority_decile, lcolor(red) mcolor(red) msymbol(circle) lwidth(medthin)), ///
        ytitle("Execution rate (%)") ///
        xtitle("Predicted priority decile") ///
        ylabel(0(25)100, grid) ///
        xlabel(1(1)10, grid) ///
        xscale(range(1 10)) ///
        legend(order(2 "P(execution | predicted priority decile)") ///
               position(6) region(lcolor(none))) ///
        graphregion(color(white)) ///
        plotregion(color(white))

    local panel_a_output "$output\figure4_panel_a_predicted_rank_fullaudits`outputsuffix'.pdf"
    capture erase "`panel_a_output'"
    graph export "`panel_a_output'", replace

    ************************************************************
    * 3. Panel B: Algorithm-selected and inspector-selected cases
    ************************************************************
    use `fullaudits', clear
    keep if algorithm == 1 & !missing(y2)
    collapse (mean) execution_algorithm = y2 (sd) sd_algorithm = y2 (count) n_algorithm = y2, by(predicted_priority_decile)
    replace sd_algorithm = 0 if missing(sd_algorithm)
    gen se_algorithm = sd_algorithm / sqrt(n_algorithm)
    gen execution_algorithm_lower = max(0, execution_algorithm - 1.96 * se_algorithm)
    gen execution_algorithm_upper = min(1, execution_algorithm + 1.96 * se_algorithm)
    replace execution_algorithm = 100 * execution_algorithm
    replace execution_algorithm_lower = 100 * execution_algorithm_lower
    replace execution_algorithm_upper = 100 * execution_algorithm_upper
    keep predicted_priority_decile execution_algorithm execution_algorithm_lower execution_algorithm_upper
    tempfile panel_b_algorithm
    save `panel_b_algorithm', replace

    use `fullaudits', clear
    keep if dgid == 1 & !missing(y2)
    collapse (mean) execution_inspector = y2 (sd) sd_inspector = y2 (count) n_inspector = y2, by(predicted_priority_decile)
    replace sd_inspector = 0 if missing(sd_inspector)
    gen se_inspector = sd_inspector / sqrt(n_inspector)
    gen execution_inspector_lower = max(0, execution_inspector - 1.96 * se_inspector)
    gen execution_inspector_upper = min(1, execution_inspector + 1.96 * se_inspector)
    replace execution_inspector = 100 * execution_inspector
    replace execution_inspector_lower = 100 * execution_inspector_lower
    replace execution_inspector_upper = 100 * execution_inspector_upper
    keep predicted_priority_decile execution_inspector execution_inspector_lower execution_inspector_upper

    merge 1:1 predicted_priority_decile using `panel_b_algorithm', nogen
    sort predicted_priority_decile

    twoway ///
        (rarea execution_algorithm_lower execution_algorithm_upper predicted_priority_decile, fcolor(maroon) fintensity(10) lcolor(maroon) lwidth(vvthin)) || ///
        (rarea execution_inspector_lower execution_inspector_upper predicted_priority_decile, fcolor(orange) fintensity(12) lcolor(orange) lwidth(vvthin)) || ///
        (connected execution_algorithm predicted_priority_decile, lcolor(maroon) mcolor(maroon) msymbol(circle) lwidth(medthin)) || ///
        (connected execution_inspector predicted_priority_decile, lcolor(orange) mcolor(orange) msymbol(triangle) lwidth(medthin)), ///
        ytitle("Execution rate (%)") ///
        xtitle("Predicted priority decile") ///
        ylabel(0(25)100, grid) ///
        xlabel(1(1)10, grid) ///
        xscale(range(1 10)) ///
        legend(order(3 "Algorithm cases" ///
                     4 "Inspector cases") ///
               rows(1) size(small) position(6) region(lcolor(none))) ///
        graphregion(color(white)) ///
        plotregion(color(white))

    local panel_b_output "$output\figure4_panel_b_predicted_rank_fullaudits`outputsuffix'.pdf"
    capture erase "`panel_b_output'"
    graph export "`panel_b_output'", replace
end

build_rank_figure4, rankinput("`rank_input_b1'")
build_rank_figure4, rankinput("`rank_input_top5'") outputsuffix("_top5excluded")
