#!/usr/bin/env python3
"""Workspace-local launcher for running Stata from VS Code tasks on Windows."""

from __future__ import annotations

import argparse
import json
import os
import re
import socket
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any, NoReturn


COMMON_STATA_PATHS = [
    Path(r"C:\Program Files\StataNow19\StataMP-64.exe"),
    Path(r"C:\Program Files\StataNow19\StataSE-64.exe"),
    Path(r"C:\Program Files\Stata19\StataMP-64.exe"),
    Path(r"C:\Program Files\Stata19\StataSE-64.exe"),
    Path(r"C:\Program Files\Stata18\StataMP-64.exe"),
    Path(r"C:\Program Files\Stata18\StataSE-64.exe"),
    Path(r"C:\Program Files\Stata17\StataMP-64.exe"),
    Path(r"C:\Program Files\Stata17\StataSE-64.exe"),
]

BROKER_SESSION_FILENAME = "session.json"
BROKER_LOG_FILENAME = "broker.log"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Launch a Stata do-file or a temporary selection do-file."
    )
    parser.add_argument(
        "--mode",
        choices=("selection", "file"),
        required=True,
        help="Whether to run the active file or the selected text.",
    )
    parser.add_argument(
        "--source-file",
        required=True,
        help="Path to the active VS Code do-file.",
    )
    parser.add_argument(
        "--keep-open",
        action="store_true",
        help="Reuse the persistent Stata GUI session instead of batch mode.",
    )
    return parser.parse_args()


def fail(message: str) -> NoReturn:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def validate_source_file(source_file_arg: str) -> Path:
    source_file = Path(source_file_arg).expanduser().resolve()
    if not source_file.exists():
        fail(f"Source do-file does not exist: {source_file}")
    if not source_file.is_file():
        fail(f"Source path is not a file: {source_file}")
    if source_file.suffix.lower() != ".do":
        fail(f"Source file must be a .do file: {source_file}")
    return source_file


def resolve_stata_executable() -> Path:
    env_value = os.environ.get("STATA_EXE", "").strip().strip('"')
    if env_value:
        stata_exe = Path(env_value).expanduser()
        if stata_exe.exists() and stata_exe.is_file():
            return stata_exe.resolve()
        fail(
            "STATA_EXE is set but does not point to an existing file: "
            f"{stata_exe}"
        )

    for candidate in COMMON_STATA_PATHS:
        if candidate.exists() and candidate.is_file():
            return candidate

    fail(
        "Could not find a Stata executable. Define STATA_EXE or install Stata in "
        "one of the common default locations checked by this launcher."
    )


def sanitize_stem(name: str) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9._-]+", "_", name).strip("._-")
    return sanitized or "selection"


def vscode_dir() -> Path:
    return Path(__file__).resolve().parent


def runtime_dir() -> Path:
    return vscode_dir() / "stata-runtime"


def broker_session_path() -> Path:
    return runtime_dir() / BROKER_SESSION_FILENAME


def broker_log_path() -> Path:
    return runtime_dir() / BROKER_LOG_FILENAME


def broker_script_path() -> Path:
    return vscode_dir() / "stata_broker.py"


def stata_quote_text(text: str) -> str:
    return text.replace('"', '""')


def create_selection_do_file(source_file: Path, selected_text: str) -> Path:
    if not selected_text.strip():
        fail(
            "No text is selected. Select Stata code in the active .do file before "
            "running 'Stata: Run selection'."
        )

    temp_dir = vscode_dir() / "stata-tmp"
    temp_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    temp_name = f"{timestamp}_{sanitize_stem(source_file.stem)}.do"
    temp_file = temp_dir / temp_name

    source_dir = source_file.parent.resolve()
    source_file_text = str(source_file)
    source_dir_text = stata_quote_text(str(source_dir))

    # Write UTF-8 so selected code is preserved even for non-ASCII comments/text.
    with temp_file.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("* Generated by VS Code task launcher.\n")
        handle.write(f"* Source do-file: {source_file_text}\n")
        handle.write(f'cd "{source_dir_text}"\n\n')
        handle.write(selected_text)
        if not selected_text.endswith("\n"):
            handle.write("\n")

    return temp_file


def build_batch_launch_args(stata_exe: Path, target_do_file: Path) -> list[str]:
    # Batch mode on Windows uses /e do <file> to run and exit without prompting.
    return [str(stata_exe), "/e", "do", str(target_do_file)]


def build_gui_launch_args(stata_exe: Path, target_do_file: Path) -> list[str]:
    # Direct GUI launch keeps Stata open but does not guarantee single-instance reuse.
    return [str(stata_exe), "do", str(target_do_file)]


def is_process_running(pid: Any) -> bool:
    try:
        os.kill(int(pid), 0)
    except (OSError, TypeError, ValueError):
        return False
    return True


def remove_stale_broker_session() -> None:
    session_path = broker_session_path()
    try:
        session_path.unlink()
    except FileNotFoundError:
        return
    except OSError:
        return


def load_broker_session() -> dict[str, Any] | None:
    session_path = broker_session_path()
    if not session_path.exists():
        return None

    try:
        session = json.loads(session_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        remove_stale_broker_session()
        return None

    if not {"host", "port", "token", "pid"}.issubset(session):
        remove_stale_broker_session()
        return None

    if not is_process_running(session["pid"]):
        remove_stale_broker_session()
        return None

    return session


def start_broker() -> dict[str, Any]:
    script_path = broker_script_path()
    if not script_path.exists():
        raise RuntimeError(f"Broker script not found: {script_path}")

    broker_runtime = runtime_dir()
    broker_runtime.mkdir(parents=True, exist_ok=True)
    remove_stale_broker_session()

    launch_args = [
        sys.executable,
        str(script_path),
        "--runtime-dir",
        str(broker_runtime),
    ]

    creationflags = 0
    if os.name == "nt":
        creationflags |= getattr(subprocess, "DETACHED_PROCESS", 0)
        creationflags |= getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0)

    with broker_log_path().open("a", encoding="utf-8") as broker_log:
        process = subprocess.Popen(
            launch_args,
            cwd=str(vscode_dir().parent),
            stdout=broker_log,
            stderr=subprocess.STDOUT,
            creationflags=creationflags,
        )

    print(f"Starting persistent Stata broker; log: {broker_log_path()}")
    deadline = time.time() + 20
    while time.time() < deadline:
        session = load_broker_session()
        if session:
            return session
        if process.poll() is not None:
            raise RuntimeError(
                "Stata broker exited during startup. Check the broker log for "
                f"details: {broker_log_path()}"
            )
        time.sleep(0.25)

    raise RuntimeError(
        "Timed out waiting for the Stata broker to start. Check the broker log "
        f"for details: {broker_log_path()}"
    )


def send_broker_request(session: dict[str, Any], payload: dict[str, Any]) -> dict[str, Any]:
    message = {
        "token": session["token"],
        "action": "run",
        "payload": payload,
    }

    try:
        with socket.create_connection(
            (session["host"], int(session["port"])),
            timeout=5,
        ) as conn:
            conn.settimeout(None)
            conn.sendall((json.dumps(message) + "\n").encode("utf-8"))
            response_data = b""
            while not response_data.endswith(b"\n"):
                chunk = conn.recv(4096)
                if not chunk:
                    break
                response_data += chunk
    except OSError as exc:
        raise ConnectionError(str(exc)) from exc

    if not response_data:
        raise ConnectionError("Broker closed the connection without a response.")

    try:
        return json.loads(response_data.decode("utf-8"))
    except json.JSONDecodeError as exc:
        raise ConnectionError("Broker returned malformed JSON.") from exc


def submit_keep_open_request(source_file: Path, target_do_file: Path) -> None:
    payload = {
        "source_file": str(source_file),
        "target_do_file": str(target_do_file),
        "cwd": str(source_file.parent.resolve()),
    }

    session = load_broker_session()
    started_new_broker = False
    if session is None:
        session = start_broker()
        started_new_broker = True

    try:
        response = send_broker_request(session, payload)
    except ConnectionError:
        remove_stale_broker_session()
        session = start_broker()
        started_new_broker = True
        response = send_broker_request(session, payload)

    if response.get("status") != "ok":
        raise RuntimeError(
            f"{response.get('error', 'Unknown broker error.')} Check the broker "
            f"log for details: {broker_log_path()}"
        )

    broker_pid = response.get("broker_pid", session["pid"])
    broker_port = response.get("broker_port", session["port"])
    session_label = "Started" if started_new_broker else "Reusing"
    print(
        f"{session_label} persistent Stata broker "
        f"(PID {broker_pid}, port {broker_port})."
    )
    print(
        f"Persistent Stata session ID: "
        f"{response.get('stata_session_id', 'unknown')}"
    )
    print(response.get("message", "Submitted request to the persistent Stata session."))


def broker_log_contains_automation_failure() -> bool:
    log_path = broker_log_path()
    if not log_path.exists():
        return False

    try:
        log_text = log_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False

    patterns = [
        "invalid class string",
        "stataoleapp",
        "automation is not registered",
    ]
    lowered = log_text.lower()
    return any(pattern in lowered for pattern in patterns)


def launch_keep_open_direct(source_file: Path, target_do_file: Path) -> None:
    stata_exe = resolve_stata_executable()
    print(
        "Stata Automation is unavailable on this machine. Falling back to a "
        "direct GUI launch, which keeps Stata open but cannot guarantee "
        "single-instance reuse."
    )
    print(f"Resolved Stata executable: {stata_exe}")
    print(f"Launching do-file: {target_do_file}")
    launch_args = build_gui_launch_args(stata_exe, target_do_file)
    subprocess.Popen(launch_args, cwd=str(source_file.parent.resolve()))


def main() -> None:
    args = parse_args()
    source_file = validate_source_file(args.source_file)

    if args.mode == "selection":
        selected_text = os.environ.get("VSCODE_SELECTED_TEXT", "")
        target_do_file = create_selection_do_file(source_file, selected_text)
    else:
        target_do_file = source_file

    if args.keep_open:
        print("Launching via persistent Stata Automation broker.")
        print(f"Target do-file: {target_do_file}")
        try:
            submit_keep_open_request(source_file, target_do_file)
        except RuntimeError as exc:
            if broker_log_contains_automation_failure():
                launch_keep_open_direct(source_file, target_do_file)
                return
            fail(str(exc))
        return

    stata_exe = resolve_stata_executable()
    print(f"Resolved Stata executable: {stata_exe}")
    print(f"Launching do-file: {target_do_file}")

    launch_args = build_batch_launch_args(stata_exe, target_do_file)
    subprocess.Popen(launch_args, cwd=str(source_file.parent.resolve()))


if __name__ == "__main__":
    main()
